# -*- coding: utf-8 -*-
"""BERT.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rtrrH-Hsaa178PtitqoAApPQQjpG5kx
"""

!pip install -q bertopic sentence-transformers umap-learn hdbscan nltk pandas

import os
import re
from collections import defaultdict

import nltk
import pandas as pd
from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired, MaximalMarginalRelevance
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer, ENGLISH_STOP_WORDS
from umap import UMAP
from google.colab import files as colab_files

def ensure_nltk():
    try:
        nltk.download("punkt",     quiet=True)
        nltk.download("punkt_tab", quiet=True)
    except Exception:
        pass

ensure_nltk()

# ── CONFIG ────────────────────────────────────────────────────────────────────
WINDOW_SIZE      = 3    # speaker turns per chunk
STRIDE           = 2    # overlap between windows
MIN_TURN_WORDS   = 5    # drop turns shorter than this
MIN_WINDOW_WORDS = 15   # drop chunks shorter than this
REDUCE_TOPICS    = True
TARGET_NR_TOPICS = 12

print("Imports done.")

CUSTOM_FILLERS = {
    "um", "uh", "uhm", "huh", "mm", "hmm", "mhm",
    "like", "know", "ya", "right", "okay", "ok",
    "yeah", "well", "alright", "just", "really",
    "kinda", "sorta", "gonna", "wanna", "gotta",
    "literally", "basically", "honestly", "actually",
}

EXTRA_NOISE_WORDS = {
    "lisa", "kate", "kylie", "kyle", "desha", "aaron", "david",
    "jayden", "addy", "michael", "tiffany", "rachel", "ondrey",
    "hunter", "jaheem", "serenitii", "alora", "curtori", "zala",
    "tyshawn", "jmarion", "anakin", "tokyo", "phoenix", "brandy",
    "miss", "mister", "mr", "ms",
    "anonymized", "identifiers", "anonymous", "transcript",
    "interview", "recording", "purposes", "consent",
    "signed", "signing", "reporting", "evaluation",
    "said", "told", "going", "thing", "things", "stuff",
    "dont", "didnt", "doesnt", "aint", "thats", "theres",
    "theyre", "youre", "got", "say", "went", "come",
}

QUESTION_STARTERS = {
    "what", "why", "how", "when", "where", "who", "which",
    "do", "did", "does", "are", "is", "can", "could",
    "would", "should", "will", "tell",
}

TOPIC_NAME_MAP = [
    ({"weed","blunt","sober","quit","smoked","drunk","addicted",
      "substance","smoking","alcohol","drink"},
     "Substance Use & Recovery"),

    ({"punch","punched","punching","hit","wall","concrete","fight",
      "fought","anger","violent","broke","bag","fist"},
     "Anger & Emotional Regulation"),

    ({"anxiety","depression","trauma","mental","health","adhd",
      "therapy","therapist","stress","nervous","overthinking",
      "panic","dissociation","did","personalities","rape","victim"},
     "Mental Health & Personal Challenges"),

    ({"nurse","nursing","cna","lpn","rn","phlebotomy","medical",
      "healthcare","clinical","hospital","vet","veterinarian"},
     "Healthcare Career Goals"),

    ({"electrician","plumber","carpenter","mechanic","trade","trades",
      "electrical","wiring","landscaping","construction","hvac",
      "diesel","welding"},
     "Trades & Skilled Labor Goals"),

    ({"law","enforcement","police","officer","military","army",
      "navy","security","cop","detective","community","patrol"},
     "Law Enforcement & Military Goals"),

    ({"stream","streamer","streaming","gaming","gamer","cosplay",
      "youtube","tiktok","content","creator","music","album",
      "singer","songwriter","artist","drawing","mural","tattoo",
      "makeup","lashes","cosmetology","bakery","culinary",
      "cook","baker","writing","writer","book","poetry",
      "computer","computers","electronics"},
     "Creative Arts, Gaming & Media Goals"),

    ({"business","owner","entrepreneur","startup","brand","publish",
      "self-employed","fafsa","college","university","degree","major"},
     "Business, College & Entrepreneurship"),

    ({"test","exam","practice","voucher","attend","classes",
      "literacy","alliance","math","essay","pass","score","studying"},
     "GED Test Preparation"),

    ({"high school","ged","school","graduated","diploma","grade",
      "tenth","ninth","eleventh","dropped","dropout","credits",
      "homeschool","online"},
     "Education & Schooling History"),

    ({"phone","verizon","att","plan","bill","sim","data",
      "android","iphone","textnow","laptop","wifi"},
     "Technology & Communication Barriers"),

    ({"money","budget","saving","spend","financial","bank","account",
      "bills","income","pay","afford","cost","broke","salary"},
     "Financial Literacy & Money Management"),

    ({"family","mom","mother","dad","father","brother","sister",
      "brothers","custody","foster","adopted","home","house",
      "grandma","grandmother","aunt","uncle"},
     "Family & Home Life"),

    ({"bus","transportation","drive","car","uber","ride",
      "commute","transit","license"},
     "Transportation Barriers"),

    ({"program","opportunity","project","connections","network",
      "resume","hire","career","skills","goals","confidence",
      "job","work","employed","fired","quit","lesson","patience"},
     "Program Goals & Job Readiness"),

    ({"jail","prison","felony","felon","arrested","criminal",
      "record","probation","monitor","ankle","court","conviction",
      "djj","charges","sentence"},
     "Criminal Justice History"),
]

def name_topic(keywords):
    all_words = set()
    for kw in keywords:
        for w in kw.lower().split():
            all_words.add(w)
        all_words.add(kw.lower())
    for trigger_set, label in TOPIC_NAME_MAP:
        if all_words & trigger_set:
            return label
    clean = [k for k in keywords[:3] if len(k) > 3]
    return " / ".join(k.title() for k in clean) if clean else "Uncategorized"

print("Noise words and topic map ready.")

LINE_RE = re.compile(
    r"^\[(\d+(?:\.\d+)?)[–\-](\d+(?:\.\d+)?)\]\s*(speaker_\d+)\s*:\s*(.*)$",
    flags=re.IGNORECASE,
)

def parse_transcript(text):
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        m = LINE_RE.match(line)
        if m:
            content = m.group(4).strip()
            if content:
                rows.append({
                    "start":    float(m.group(1)),
                    "end":      float(m.group(2)),
                    "speaker":  m.group(3).lower(),
                    "content":  content,
                    "raw_line": line,
                })
    return rows

def looks_like_question(text):
    t = text.strip().lower()
    if "?" in t:
        return True
    starters = (
        "what", "why", "how", "when", "where", "who", "which",
        "do you", "did you", "are you", "have you", "can you",
        "could you", "would you", "should you", "will you",
        "tell me", "describe", "explain",
    )
    return any(t.startswith(s) for s in starters)

def detect_participant_speaker(rows):
    if not rows:
        return None
    by_spk = defaultdict(list)
    for row in rows:
        by_spk[row["speaker"]].append(row["content"])
    if len(by_spk) == 1:
        return list(by_spk.keys())[0]
    scores = {}
    for spk, turns in by_spk.items():
        n       = len(turns)
        q       = sum(1 for t in turns if looks_like_question(t))
        avg_len = sum(len(t.split()) for t in turns) / max(n, 1)
        q_ratio = q / max(n, 1)
        scores[spk] = {
            "score":       (2.0 * q_ratio) + (1.0 / (1.0 + avg_len)),
            "q_ratio":     q_ratio,
            "avg_len":     avg_len,
            "total_words": sum(len(t.split()) for t in turns),
        }
    ranked = sorted(scores.items(), key=lambda kv: kv[1]["score"], reverse=True)
    top_spk, top_stats = ranked[0]
    _, second_stats    = ranked[1]
    if (top_stats["q_ratio"] >= 0.15
            and (top_stats["score"] - second_stats["score"]) >= 0.10):
        others = [s for s in by_spk if s != top_spk]
        if len(others) == 1:
            return others[0]
    fallback = {
        spk: (1.5 * s["total_words"] + 2.0 * s["avg_len"]
              - 10.0 * sum(1 for t in by_spk[spk] if looks_like_question(t)))
        for spk, s in scores.items()
    }
    return max(fallback, key=fallback.get)

print("Parsing functions ready.")

CONTRACTIONS = [
    (r"\bi'ma\b",      "i am"),
    (r"\bim\b",        "i am"),
    (r"\bive\b",       "i have"),
    (r"\byoure\b",     "you are"),
    (r"\bthats\b",     "that is"),
    (r"\btheres\b",    "there is"),
    (r"\bwanna\b",     "want to"),
    (r"\bgonna\b",     "going to"),
    (r"\bgotta\b",     "have to"),
    (r"\bdont\b",      "do not"),
    (r"\bdidnt\b",     "did not"),
    (r"\bdoesnt\b",    "does not"),
    (r"\bcant\b",      "can not"),
    (r"\bwont\b",      "will not"),
    (r"\baint\b",      "are not"),
    (r"\bcuz\b",       "because"),
    (r"'cause",        " because "),
    (r"'because",      " because "),
    (r"\bg\s*e\s*d\b", "ged"),
    (r"\bg\s*d\b",     "ged"),
    (r"\bd\s*j\s*j\b", "djj"),
    (r"\bl\s*p\s*n\b", "lpn"),
    (r"\bc\s*n\s*a\b", "cna"),
]

def normalize_turn(text):
    text = text.lower()
    text = re.sub(r"(\w+)'(\w+)", r"\1 \2", text)
    for pattern, replacement in CONTRACTIONS:
        text = re.sub(pattern, f" {replacement} ", text, flags=re.IGNORECASE)
    text = re.sub(r"[^\w\s]", " ", text)
    for filler in sorted(CUSTOM_FILLERS, key=len, reverse=True):
        text = re.sub(rf"\b{re.escape(filler)}\b", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"\b\d{3,}\b", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def prepare_documents(transcripts_dict):
    docs     = []
    doc_rows = []
    all_rows = {}
    for filename, raw_text in transcripts_dict.items():
        rows = parse_transcript(raw_text)
        if not rows:
            continue
        all_rows[filename] = rows
        participant = detect_participant_speaker(rows)
        if participant is None:
            continue
        participant_turns = []
        for row in rows:
            if row["speaker"] == participant:
                cleaned = normalize_turn(row["content"])
                if len(cleaned.split()) >= MIN_TURN_WORDS:
                    participant_turns.append(cleaned)
        if len(participant_turns) < 2:
            continue
        n = len(participant_turns)
        for start in range(0, n, STRIDE):
            end   = start + WINDOW_SIZE
            chunk = " ".join(participant_turns[start:end]).strip()
            if len(chunk.split()) >= MIN_WINDOW_WORDS:
                docs.append(chunk)
                doc_rows.append({"filename": filename, "document": chunk})
            if end >= n:
                break
    return docs, pd.DataFrame(doc_rows), all_rows

print("Normalisation and document prep ready.")

def build_topic_model():
    custom_stop_words = list(
        ENGLISH_STOP_WORDS.union(CUSTOM_FILLERS).union(EXTRA_NOISE_WORDS)
    )
    vectorizer_model = CountVectorizer(
        stop_words=custom_stop_words,
        min_df=2,
        max_df=0.85,
        ngram_range=(1, 2),
        token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z]{2,}\b",
    )
    umap_model = UMAP(
        n_neighbors=15, n_components=5,
        min_dist=0.1, metric="cosine", random_state=42,
    )
    hdbscan_model = HDBSCAN(
        min_cluster_size=8, min_samples=2,
        metric="euclidean", cluster_selection_method="eom",
        prediction_data=True,
    )
    representation_model = {
        "Main": KeyBERTInspired(),
        "MMR":  MaximalMarginalRelevance(diversity=0.5),
    }
    return BERTopic(
        vectorizer_model=vectorizer_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        representation_model=representation_model,
        top_n_words=10,
        calculate_probabilities=True,
        verbose=True,
    )

def compute_topic_scores(topic_model, topics):
    topic_info = topic_model.get_topic_info()
    total_docs  = sum(1 for t in topics if t != -1)
    rows = []
    for _, row in topic_info.iterrows():
        tid = row["Topic"]
        if tid == -1:
            continue
        kw_list   = topic_model.get_topic(tid) or []
        keywords  = [w for w, _ in kw_list]
        kw_scores = [s for _, s in kw_list]
        doc_count     = int(row["Count"])
        doc_pct       = round(doc_count / max(total_docs, 1) * 100, 1)
        keyword_score = round(sum(kw_scores) / max(len(kw_scores), 1), 4)
        composite     = round(
            0.4 * doc_pct + 0.4 * (keyword_score * 100) + 0.2 * min(doc_count / 5, 10), 2
        )
        rows.append({
            "topic_id":        tid,
            "topic_name":      name_topic(keywords),
            "doc_count":       doc_count,
            "doc_pct":         doc_pct,
            "composite_score": composite,
            "keyword_score":   keyword_score,
            "top_keywords":    ", ".join(keywords[:8]),
        })
    df = (pd.DataFrame(rows)
            .sort_values("composite_score", ascending=False)
            .reset_index(drop=True))
    df.insert(0, "rank", range(1, len(df) + 1))
    return df

def build_transcript_links(topic_model, docs_df, all_rows, scored_topics):
    topic_kws = {}
    for tid in scored_topics["topic_id"]:
        kw_list = topic_model.get_topic(tid) or []
        words   = set()
        for phrase, _ in kw_list:
            for w in phrase.lower().split():
                if len(w) > 3:
                    words.add(w)
        topic_kws[tid] = words
    link_rows = []
    for _, topic_row in scored_topics.iterrows():
        tid   = int(topic_row["topic_id"])
        tname = topic_row["topic_name"]
        kws   = topic_kws.get(tid, set())
        if not kws:
            continue
        files_in_topic = docs_df[docs_df["topic"] == tid]["filename"].unique()
        for fname in files_in_topic:
            rows = all_rows.get(fname, [])
            if not rows:
                continue
            matched = [
                row for row in rows
                if sum(1 for kw in kws if kw in row["content"].lower()) >= 1
            ]
            if not matched:
                continue
            matched.sort(key=lambda r: r["start"])
            link_rows.append({
                "topic_id":      tid,
                "topic_name":    tname,
                "filename":      fname,
                "start_time":    matched[0]["start"],
                "end_time":      matched[-1]["end"],
                "line_count":    len(matched),
                "matched_lines": "\n".join(r["raw_line"] for r in matched),
            })
    return pd.DataFrame(link_rows)

print("Model, scoring, and linking functions ready.")

# Upload all 19 transcript .txt files when prompted
print("Upload your transcript .txt files now.")
uploaded    = colab_files.upload()
transcripts = {}
for fname, data in uploaded.items():
    try:
        transcripts[fname] = data.decode("utf-8")
    except UnicodeDecodeError:
        transcripts[fname] = data.decode("latin-1")
print(f"\nLoaded {len(transcripts)} transcripts.")

# Build document chunks
docs, docs_df, all_rows = prepare_documents(transcripts)
print(f"{len(docs)} document chunks created.")

if len(docs) < 20:
    raise ValueError(f"Only {len(docs)} chunks — too few. Check your files.")

# Fit BERTopic
topic_model   = build_topic_model()
topics, probs = topic_model.fit_transform(docs)

# Reduce to 12 topics
topic_model = topic_model.reduce_topics(docs, nr_topics=TARGET_NR_TOPICS)
topics      = topic_model.topics_

# Score topics
docs_df["topic"] = topics
scored_topics    = compute_topic_scores(topic_model, topics)

print("\nTopic Scores:")
print(scored_topics[["rank","topic_name","doc_count","doc_pct","composite_score"]]
      .to_string(index=False))

# Link topics to transcript lines
transcript_links = build_transcript_links(
    topic_model, docs_df, all_rows, scored_topics
)
print(f"Linked {len(transcript_links)} topic-transcript pairs.")

# Save CSVs
scored_topics.to_csv("/content/topic_scores.csv",        index=False)
transcript_links.to_csv("/content/transcript_links.csv", index=False)
docs_out = docs_df.copy()
docs_out.to_csv("/content/document_topics.csv", index=False)

# Save BERTopic visuals
topic_model.visualize_barchart().write_html("/content/barchart.html")
topic_model.visualize_topics().write_html("/content/topics_overview.html")
valid = [t for t in topic_model.get_topic_info()["Topic"] if t != -1]
if len(valid) >= 2:
    topic_model.visualize_hierarchy(topics=valid).write_html("/content/topics_hierarchy.html")
    topic_model.visualize_heatmap(topics=valid).write_html("/content/topics_heatmap.html")

print("All files saved.")

import os

files_to_download = [
    "/content/topic_scores.csv",
    "/content/transcript_links.csv",
    "/content/document_topics.csv",
    "/content/barchart.html",
    "/content/topics_overview.html",
    "/content/topics_hierarchy.html",
    "/content/topics_heatmap.html",
]

for path in files_to_download:
    if os.path.exists(path):
        print(f"Downloading {os.path.basename(path)}...")
        colab_files.download(path)

print("\nDone. Check your browser Downloads folder.")