# -*- coding: utf-8 -*-
"""WorkingNew.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iah9zdEahIxj2rbqBNyYGQbQsv4rdA6J
"""

from google.colab import drive
drive.mount('/content/drive')

import os
from pathlib import Path

# INPUT from Drive
INPUT_DIR = Path("/content/drive/MyDrive/AudioInterview")

# WORK + OUTPUT on Colab local disk
WORK_DIR = Path("/content/work")         # converted wavs, temp
OUT_DIR  = Path("/content/outputs")      # final outputs per file

WORK_DIR.mkdir(parents=True, exist_ok=True)
OUT_DIR.mkdir(parents=True, exist_ok=True)

m4a_files = sorted(INPUT_DIR.rglob("*.m4a"))
print("Found .m4a:", len(m4a_files))
for p in m4a_files[:10]:
    print(" -", p.name)

import re, subprocess
from tqdm import tqdm

def safe_stem(name: str) -> str:
    s = re.sub(r"\s+", " ", name).strip()
    s = re.sub(r"[^\w\-\.\s]", "", s)
    return s.replace(" ", "_")

def m4a_to_wav(m4a_path: Path, wav_root: Path) -> Path:
    session_id = safe_stem(m4a_path.stem)
    wav_path = wav_root / f"{session_id}.wav"

    if wav_path.exists() and wav_path.stat().st_size > 0:
        return wav_path

    cmd = [
        "ffmpeg", "-y",
        "-i", str(m4a_path),
        "-ac", "1",          # mono
        "-ar", "16000",      # 16k
        "-vn",
        str(wav_path)
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return wav_path

wav_files = []
for m4a in tqdm(m4a_files, desc="Converting m4a→wav"):
    wav_files.append(m4a_to_wav(m4a, WORK_DIR))

print("WAV ready:", len(wav_files))
print("Example:", wav_files[0])

import os, sys, json, math, re, time, shutil, subprocess
from pathlib import Path
import numpy as np

# NumPy guard (common Colab break: numpy 2.x vs some deps)
# If you still get "numpy.dtype size changed" errors later, rerun this and restart runtime.
try:
    import numpy
    print("NumPy version:", numpy.__version__)
except Exception as e:
    print("NumPy import issue:", e)

# Device
import torch
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE, "| torch:", torch.__version__)

!apt-get -y update
!apt-get -y install ffmpeg sox libsndfile1

!pip -q install soundfile librosa tqdm pandas

import nemo.collections.asr as nemo_asr

ASR_MODEL_NAME = "nvidia/parakeet-tdt-0.6b-v3"
print("Loading ASR:", ASR_MODEL_NAME)

asr_model = nemo_asr.models.ASRModel.from_pretrained(
    model_name=ASR_MODEL_NAME,
    map_location=torch.device(DEVICE)
)
asr_model.eval()

print("ASR loaded on:", DEVICE)

from omegaconf import OmegaConf
from tqdm import tqdm

CONF_DIR = Path("/content/conf_diar")
CONF_DIR.mkdir(parents=True, exist_ok=True)

DIAR_YAML = CONF_DIR / "diar_infer.yaml"
if not DIAR_YAML.exists():
    !wget -q -O /content/conf_diar/diar_infer.yaml https://raw.githubusercontent.com/NVIDIA/NeMo/main/examples/speaker_tasks/diarization/conf/inference/diar_infer_general.yaml

cfg = OmegaConf.load(str(DIAR_YAML))
print("Loaded diarization config:", DIAR_YAML)

DIAR_WORK = Path("/content/diar_work")
DIAR_WORK.mkdir(parents=True, exist_ok=True)

def run_nemo_diarization(wav_path: Path, session_out: Path) -> Path:
    """
    Runs NeMo diarization inference on wav_path and writes RTTM into session_out.
    Returns RTTM path.
    """
    session_out.mkdir(parents=True, exist_ok=True)
    rttm_out = session_out / f"{wav_path.stem}.rttm"

    # Create a minimal diarization manifest
    manifest_path = session_out / f"{wav_path.stem}.diar_manifest.json"
    audio_len_sec = None

    # Use librosa to compute duration safely
    import librosa
    y, sr = librosa.load(str(wav_path), sr=16000, mono=True)
    audio_len_sec = float(len(y) / sr)

    diar_manifest_line = {
        "audio_filepath": str(wav_path),
        "offset": 0,
        "duration": audio_len_sec,
        "label": "infer",
        "text": "-",
        "num_speakers": None,  # let diarizer estimate
        "rttm_filepath": None,
        "uem_filepath": None
    }
    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write(json.dumps(diar_manifest_line) + "\n")

    # Patch config
    local_cfg = OmegaConf.create(OmegaConf.to_container(cfg, resolve=True))
    local_cfg.diarizer.manifest_filepath = str(manifest_path)
    local_cfg.diarizer.out_dir = str(session_out)

    # Tenable msdd / neural refinement if config supports it
    # (If not available, NeMo will still produce RTTM from clustering diarization.)
    # These are common model names shipped via NGC:
    # - "titanet_large" for embeddings
    # - "diar_msdd_telephonic" for MS-DD refinement (if present in your NeMo build)
    try:
        local_cfg.diarizer.speaker_embeddings.model_path = "titanet_large"
    except Exception:
        pass

    # Attempt MS-DD refinement setup
    try:
        local_cfg.diarizer.msdd_model.model_path = "diar_msdd_telephonic"
        local_cfg.diarizer.msdd_model.parameters.use_embedding_features = True
    except Exception:
        pass

    # Run diarization
    try:
        from nemo.collections.asr.models import ClusteringDiarizer
        diarizer = ClusteringDiarizer(cfg=local_cfg)
        diarizer.diarize()

        # NeMo writes RTTM under out_dir/pred_rttms by default in many configs
        pred_dir = session_out / "pred_rttms"
        candidates = list(pred_dir.glob("*.rttm")) if pred_dir.exists() else []
        if not candidates:
            # Sometimes in "rttms" or directly in out_dir
            candidates = list(session_out.rglob("*.rttm"))

        # Pick the RTTM that matches this file
        picked = None
        for c in candidates:
            if wav_path.stem in c.name:
                picked = c
                break
        if picked is None and candidates:
            picked = candidates[0]

        if picked is None:
            raise FileNotFoundError("No RTTM produced by diarizer.")

        # Copy to standardized location/name
        shutil.copy2(picked, rttm_out)
        return rttm_out

    except Exception as e:
        raise RuntimeError(f"Diarization failed for {wav_path.name}: {e}")

import pandas as pd

def parse_rttm(rttm_path: Path):
    """
    RTTM format line example:
    SPEAKER file 1 start dur <NA> <NA> speaker_id <NA> <NA>
    """
    segments = []
    with open(rttm_path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.strip().split()
            if len(parts) < 9:
                continue
            if parts[0] != "SPEAKER":
                continue
            start = float(parts[3])
            dur = float(parts[4])
            spk = parts[7]
            segments.append((start, start + dur, spk))

    segments.sort(key=lambda x: (x[0], x[2]))
    return segments

def merge_segments(segments, max_gap=0.35, min_dur=0.25):
    """
    Merge consecutive segments of same speaker if gap <= max_gap.
    Drop ultra-short segments (< min_dur).
    """
    if not segments:
        return []

    merged = []
    cur_s, cur_e, cur_spk = segments[0]

    for s, e, spk in segments[1:]:
        if spk == cur_spk and (s - cur_e) <= max_gap:
            cur_e = max(cur_e, e)
        else:
            if (cur_e - cur_s) >= min_dur:
                merged.append((cur_s, cur_e, cur_spk))
            cur_s, cur_e, cur_spk = s, e, spk

    if (cur_e - cur_s) >= min_dur:
        merged.append((cur_s, cur_e, cur_spk))

    return merged

import soundfile as sf
import librosa

TMP_AUDIO_DIR = Path("/content/tmp_asr")
TMP_AUDIO_DIR.mkdir(parents=True, exist_ok=True)

def write_wav_slice(full_wav: Path, start_s: float, end_s: float, out_path: Path, sr=16000):
    y, _ = librosa.load(str(full_wav), sr=sr, mono=True, offset=max(0.0, start_s), duration=max(0.0, end_s-start_s))
    sf.write(str(out_path), y, sr)
    return out_path

def asr_transcribe_wav_paths(wav_paths, batch_size=8):
    # NeMo transcribe expects list of filepaths
    hypotheses_or_texts = asr_model.transcribe([str(p) for p in wav_paths], batch_size=batch_size)
    # extract the text from Hypothesis objects if they are returned
    texts = []
    for h_or_t in hypotheses_or_texts:
        if hasattr(h_or_t, 'text'):
            texts.append(h_or_t.text)
        else:
            texts.append(str(h_or_t)) # Fallback if it's already a string or something else
    return texts

def transcribe_segment_chunked(full_wav: Path, start_s: float, end_s: float,
                              max_chunk_s=25.0, overlap_s=2.0):
    """
    Transcribe [start_s, end_s] by chunking into smaller wav files.
    """
    duration = end_s - start_s
    if duration <= 0.05:
        return ""

    # If short enough, do one shot
    if duration <= max_chunk_s:
        tmp = TMP_AUDIO_DIR / f"{full_wav.stem}_{start_s:.2f}_{end_s:.2f}.wav".replace("..",".")
        write_wav_slice(full_wav, start_s, end_s, tmp)
        return asr_transcribe_wav_paths([tmp], batch_size=1)[0].strip()

    # Else chunk with overlap
    cur = start_s
    chunks = []
    chunk_paths = []
    while cur < end_s - 0.05:
        chunk_end = min(cur + max_chunk_s, end_s)
        tmp = TMP_AUDIO_DIR / f"{full_wav.stem}_{cur:.2f}_{chunk_end:.2f}.wav".replace("..",".")
        write_wav_slice(full_wav, cur, chunk_end, tmp)
        chunk_paths.append(tmp)
        chunks.append((cur, chunk_end))
        if chunk_end >= end_s:
            break
        cur = chunk_end - overlap_s  # overlap

    # Batch transcribe
    texts = []
    B = 8 if DEVICE == "cuda" else 2
    for i in range(0, len(chunk_paths), B):
        texts.extend(asr_transcribe_wav_paths(chunk_paths[i:i+B], batch_size=B))

    # Simple merge
    merged = " ".join([t.strip() for t in texts if t and t.strip()])
    return merged.strip()

def srt_timestamp(t: float) -> str:
    # SRT timestamp: HH:MM:SS,mmm
    if t < 0:
        t = 0.0
    ms = int(round((t - int(t)) * 1000))
    total = int(t)
    s = total % 60
    m = (total // 60) % 60
    h = (total // 3600)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

def write_srt(entries, out_path: Path):
    """
    entries: list of dict {start, end, speaker, text}
    """
    lines = []
    for i, e in enumerate(entries, 1):
        lines.append(str(i))
        lines.append(f"{srt_timestamp(e['start'])} --> {srt_timestamp(e['end'])}")
        # speaker label in SRT line
        spk = e["speaker"]
        txt = e["text"].strip()
        lines.append(f"{spk}: {txt}" if txt else f"{spk}:")
        lines.append("")  # blank line
    out_path.write_text("\n".join(lines), encoding="utf-8")

def build_outputs_for_file(full_wav: Path, session_out: Path, original_name: str = None):
    """
    Produces:
      - RTTM (copied standardized)
      - segments CSV
      - jsonl for BERTopic
      - readable txt
      - srt
    """
    session_out.mkdir(parents=True, exist_ok=True)

    # 1) diarization
    rttm_path = run_nemo_diarization(full_wav, session_out)

    # 2) parse + merge
    segs = merge_segments(parse_rttm(rttm_path), max_gap=0.35, min_dur=0.25)

    # 3) ASR each segment (chunked)
    rows = []
    srt_entries = []

    for (s, e, spk) in tqdm(segs, desc=f"ASR {full_wav.name}", leave=False):
        text = transcribe_segment_chunked(full_wav, s, e, max_chunk_s=25.0, overlap_s=2.0)

        row = {
            "file_id": full_wav.stem,
            "original_file": original_name or "",
            "speaker": spk,
            "start": round(s, 3),
            "end": round(e, 3),
            "duration": round(e - s, 3),
            "text": text
        }
        rows.append(row)

        srt_entries.append({
            "start": float(s),
            "end": float(e),
            "speaker": spk,
            "text": text
        })

    # 4) Save CSV + JSONL
    df = pd.DataFrame(rows)
    csv_path = session_out / f"{full_wav.stem}.segments.csv"
    jsonl_path = session_out / f"{full_wav.stem}.segments.jsonl"
    txt_path = session_out / f"{full_wav.stem}.transcript.txt"
    srt_path = session_out / f"{full_wav.stem}.srt"

    df.to_csv(csv_path, index=False, encoding="utf-8")
    with open(jsonl_path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    # 5) Save readable transcript TXT
    # (speaker-tagged timeline)
    lines = []
    for r in rows:
        lines.append(f"[{r['start']:.2f}–{r['end']:.2f}] {r['speaker']}: {r['text']}".strip())
    txt_path.write_text("\n".join(lines), encoding="utf-8")

    # 6) Save SRT
    write_srt(srt_entries, srt_path)

    return {
        "rttm": str(rttm_path),
        "csv": str(csv_path),
        "jsonl": str(jsonl_path),
        "txt": str(txt_path),
        "srt": str(srt_path),
        "num_segments": len(rows)
    }

def safe_stem(name: str) -> str:
    s = re.sub(r"\s+", " ", name).strip()
    s = re.sub(r"[^\w\-\.\s]", "", s)
    return s.replace(" ", "_")

results = []

for wav_path in tqdm(wav_files, desc="Full pipeline"):
    # Map back to original filename if you want (best-effort)
    # (If you want perfect mapping, store it in Cell B when converting.)
    session_id = safe_stem(wav_path.stem)
    session_out = OUT_DIR / session_id

    try:
        out = build_outputs_for_file(
            full_wav=Path(wav_path),
            session_out=session_out,
            original_name=""  # optionally fill with original m4a name
        )
        results.append({"file": wav_path.name, **out})
        print(f"Done: {wav_path.name} | segments={out['num_segments']}")
    except Exception as e:
        print(f"Failed: {wav_path.name}\n   {e}")
        # keep going

# Summary
import pandas as pd
summary_df = pd.DataFrame(results)
summary_path = OUT_DIR / "SUMMARY.csv"
summary_df.to_csv(summary_path, index=False)
print("Wrote summary:", summary_path)
summary_df.head()

# optional cleanup to reduce disk usage
# shutil.rmtree(TMP_AUDIO_DIR, ignore_errors=True)
print("Temp dir:", TMP_AUDIO_DIR, "exists?", TMP_AUDIO_DIR.exists())

from google.colab import files
import shutil

zip_base = "/content/AudioInterview_outputs"
zip_path = shutil.make_archive(zip_base, 'zip', root_dir=str(OUT_DIR))

print("Zipped:", zip_path)
files.download(zip_path)

